export const order_baseUrl = '/api/orders'
export const product_baseUrl = '/api/products'
export const package_baseUrl = '/api/packages'
export const detail_baseUrl = '/api/details'
export const log_baseUrl = '/api/logs'
